global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Backend API metrics
  - job_name: 'eco-backend'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    scheme: http
    static_configs:
      - targets: ['backend_1:3001']
        labels:
          instance: 'backend-1'
          service: 'eco-water-backend'
          environment: 'development'
      - targets: ['backend_2:3001']
        labels:
          instance: 'backend-2'
          service: 'eco-water-backend'
          environment: 'development'

  # NGINX metrics (if nginx-prometheus-exporter is added)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:8080']
    metrics_path: '/nginx_status'
    scrape_interval: 15s
    
  # MongoDB metrics (if mongodb_exporter is added)
  - job_name: 'mongodb'
    static_configs:
      - targets: []  # Would be mongodb_exporter:9216
    scrape_interval: 30s
    
  # Redis metrics (if redis_exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: []  # Would be redis_exporter:9121
    scrape_interval: 30s

  # Node exporter for system metrics (if added)
  - job_name: 'node'
    static_configs:
      - targets: []  # Would be node_exporter:9100
    scrape_interval: 30s

# Remote write configuration (for production)
# remote_write:
#   - url: "https://prometheus-remote-write-endpoint"
#     basic_auth:
#       username: "user"
#       password: "password"
